### ISSUE TITLE
dict contains fields not in fieldnames: 'seats_F'

### ISSUE THREAD

**Issue by miguelgarciaalfaro** [Schiphol-Hub/ssim#18]
Hello,

I am trying to parse an SSIM file but not able to do it as I got the next error, do you know what does it mean?

2023-09-20 19:37:19,608] INFO: Expanded 15546 slots into 384146 flights.
Traceback (most recent call last):
  File "/usr/local/bin/ssim", line 8, in <module>
    sys.exit(main())
  File "/Users/miguelgarciaalfaro/Library/Python/3.8/lib/python/site-packages/ssim/__main__.py", line 23, in main
    dict_writer.writerows(flights)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'seats_F'

Thank you

**Comment by ramonvanschaik** [comment]
Hey there. Easiest way for us to check what's going on is if we can attempt to load your file ourselves. Can you share the file with us, or does it contain confidential info?
