### ISSUE TITLE
ValueError: Could not find required header information in file:

### ISSUE THREAD

**Issue by linusnorton** [Schiphol-Hub/ssim#2]
Hello,

Thanks for providing this utility. I am having some trouble processing a sample SSID file, the error I get is:

```[2018-08-08 12:27:59,529] INFO: Reading and parsing slotfile: sample.SCR.
Traceback (most recent call last):
  File "/usr/local/bin/ssim", line 11, in <module>
    load_entry_point('ssim==0.2.1', 'console_scripts', 'ssim')()
  File "/usr/local/lib/python2.7/dist-packages/ssim/__main__.py", line 15, in main
    slots, _, _ = ssim.read(input_file)
  File "/usr/local/lib/python2.7/dist-packages/ssim/ssim.py", line 537, in read
    slots, header, footer = _parse_slotfile(text, year_prefix=year_prefix)
  File "/usr/local/lib/python2.7/dist-packages/ssim/ssim.py", line 236, in _parse_slotfile
    raise ValueError('Could not find required header information in file:\n%s' % text[0:200])
ValueError: Could not find required header information in file:
1AIRLINE STANDARD SCHEDULE DATA SET      COPYRIGHT 2008, OAG WORLDWIDE LTD.  ALL RIGHTS RESERVED.                       18MAY08                                                                001000001
```

I assume there is a problem with my data. The first 20 lines look like:

```1AIRLINE STANDARD SCHEDULE DATA SET      COPYRIGHT 2008, OAG WORLDWIDE LTD.  ALL RIGHTS RESERVED.                       18MAY08                                                                001000001
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2LCA R0008S08 07MAY0800XXX0007MAY08OAG SSIM PRODUCT             18MAY08C                                                                                                                    EN1937000002
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
3 CA  1010101J12MAY0813MAY0812      PEK08000800+08003 HKG11251125+08001 738CDIJYBMHKLQGSXVUZWTE     XX                 II                                        M                              00000003
4 CA  1010101J              AB010PEKHKGCX 6101 /KA 1101                                                                                                                                           000004
4 CA  1010101J              AB109PEKHKGB B B B B B B B B B B B B B B B B B B B                                                                                                                    000005
4 CA  1010101J              AB503PEKHKG  9                                                                                                                                                        000006
4 CA  1010101J              AB505PEKHKGET                                                                                                                                                         000007
3 CA  1010201J14MAY0815MAY08  34    PEK08000800+08003 HKG11251125+08001 738CDIJYBMHKLQGSXVUZWTE     XX                 II                                        M                              00000008
4 CA  1010201J              AB010PEKHKGCX 6101 /KA 1101                                                                                                                                           000009
4 CA  1010201J              AB109PEKHKGB B B B B B B B B B B B B B B B B B B B                                                                                                                    000010
4 CA  1010201J              AB503PEKHKG  9                                                                                                                                                        000011
4 CA  1010201J              AB505PEKHKGET                                                                                                                                                         000012
```

Do you know what the problem might be?

**Comment by rok** [comment]
Hey @linusnorton - it's probably that the 5th line is doing something unexpected by the parser. I'll try to take a look at it tonight.

**Comment by linusnorton** [comment]
Thanks, I got the file from: https://github.com/tuananh/opentravel/tree/develop/data/ssim

Hopefully I should have a more recently sample coming from OAG at some point.

**Comment by schaikr** [comment]
Hi Linus, good to hear it's of service to other people as well :). Are you using the pip installed version or did you clone directly of github? The github-version is a little ahead of the pip verison, especially regarding SSIM. Because I don't get the same error you do, I assume you're on the version from pip? Also, I assume the mentioned row from the ValueError (starting with `1AIRLINE STANDARD SCHEDULE DATA SET ` is present in your original data file?

I do get another error, however. Your data file seems to be in local time (indicated by 2L on row 5/6). I wasn't able to test local time support yet, so in order to prevent costly mistakes, I disabled it with a hard check. If you can export your data in UTC, that would bypass the issue. Either way, it's a good motivation to get LT support implemented, tested and rolled out to a new pip version.

**Comment by rok** [comment]
@linusnorton - indeed your file is missing the first line of the header. If you input:
```
1AIRLINE STANDARD SCHEDULE DATA SET      COPYRIGHT 2008, OAG WORLDWIDE LTD.  ALL RIGHTS RESERVED.                       18MAY08                                                                001000001
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2UCA R0008S08 07MAY0800XXX0007MAY08OAG SSIM PRODUCT             18MAY08C                                                                                                                    EN1937000002
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
3 CA  1010101J12MAY0813MAY0812      PEK08000800+08003 HKG11251125+08001 738CDIJYBMHKLQGSXVUZWTE     XX                 II                                        M                              00000003
4 CA  1010101J              AB010PEKHKGCX 6101 /KA 1101                                                                                                                                           000004
4 CA  1010101J              AB109PEKHKGB B B B B B B B B B B B B B B B B B B B                                                                                                                    000005
4 CA  1010101J              AB503PEKHKG  9                                                                                                                                                        000006
4 CA  1010101J              AB505PEKHKGET                                                                                                                                                         000007
3 CA  1010201J14MAY0815MAY08  34    PEK08000800+08003 HKG11251125+08001 738CDIJYBMHKLQGSXVUZWTE     XX                 II                                        M                              00000008
4 CA  1010201J              AB010PEKHKGCX 6101 /KA 1101                                                                                                                                           000009
4 CA  1010201J              AB109PEKHKGB B B B B B B B B B B B B B B B B B B B                                                                                                                    000010
4 CA  1010201J              AB503PEKHKG  9                                                                                                                                                        000011
4 CA  1010201J              AB505PEKHKGET                                                                                                                                                         000012
```
it will work.

However notice the local versus UTC setting @schaikr mentioned. Currently processing `2UCA` will work and `2LCA` will fail. We'll address this and make a new distribution to pypi.

**Comment by linusnorton** [comment]
Thanks, I am currently using the pip version. Let me know when a new version is pushed and I'll give it a try.

**Comment by rok** [comment]
Hey @linusnorton!
A new release is out on pypi and is pip installable.

@schaikr: As for the time_mode issue: I've implemented a way to handle local/UTC sim files. Time zone information now gets added to the time of arrival and departure. If the time mode is UTC it will be XXXX+0000, if it is local it will be XXXX+YYYY., where XXXX is the time and YYYY is local to UTC difference.

**Comment by linusnorton** [comment]
Thanks, I'm away at the moment but will give it a try next week

**Comment by linusnorton** [comment]
Hi,

I can report some progress, but I do get another error now:

```
ValueError: Found infinity indicator 00XXX00 in file, but no season specified. Pleas sepcify season. 
3 CA  1011501J26OCT0800XXX001234567 PEK08000800+08003 HKG11251125+08001 738CDIJYBMHKLQGSXVUZWTE     XX                 II                                        M                              00000073
```

It seems like a reasonable complaint so I'm wondering if the file OAG have provided is just invalid.

**Comment by schaikr** [comment]
At least one of the lines in your file contains an infinity indication. So in the line mentioned in the error the operation commences at 26OCT08 and ends at 00XXX00 (=infinity). In current design we expected SSIM files always to contain one IATA season, so `expand_slots` can let the flights continue until the end of IATA season with the season argument. In this case I would expect that to be W08, so you should provide that as an argument:

`flights = ssim.expand_slots(slots, season='W08')`

In case your file is supposed to stretch longer than one season, let us know, because then we might need to rethink this approach.

**Comment by linusnorton** [comment]
I'm currently using the tool from the CLI. I'll dust off my python skills and see if I can use the API

**Comment by linusnorton** [comment]
I have too many values to unpack:

```
linus@portaloo:~/Downloads/ssim$ cat main.py 
import ssim

slots, header, footer = ssim.read('data.txt')
flights = ssim.expand_slots(slots, season='W08')

linus@portaloo:~/Downloads/ssim$ python main.py 
[2018-08-22 10:04:59,473] INFO: Reading and parsing SIM file: data.txt.
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    slots, header, footer = ssim.read('data.txt')
ValueError: too many values to unpack
```

**Comment by schaikr** [comment]
Whoops, think manual is outdated. Can you try:

`slots = ssim.read('data.txt')`
`flights = ssim.expand_slots(slots, season='W08')`
